#!/bin/bash

set -e

export crt_path=$1

if [ -n "$crt_path" ];
then

	echo "$(tput setaf 6)Showing the certificate info...$(tput sgr0)"
	openssl x509 -inform DER -in $crt_path/*_asppb_authority.cer -text -noout
	echo
	
	echo "$(tput setaf 6)Converting certificate from DER format to CRT format (binary x509 encoded in base64 encoding)...$(tput sgr0)"
	openssl x509 -inform DER -in $crt_path/*_asppb_authority.cer -out $crt_path/*_asppb_authority.crt
	
	echo "$(tput setaf 6)Showing the converted certificate info...$(tput sgr0)"
	openssl x509 -in $crt_path/*_asppb_authority.crt -text -noout
	echo
	
	echo "$(tput setaf 6)Copying root certificate to certificate import folder (/usr/local/share/ca-certificates/)...$(tput sgr0)"
	cp $crt_path/*_asppb_authority.crt /usr/local/share/ca-certificates/
	
	echo "$(tput setaf 6)Updating the system storage of root certificates...$(tput sgr0)"
	update-ca-certificates -v
	echo

	echo "$(tput setaf 6)Copying files to MobileBooking: cl-GUID.pfx, pwd.txt, LOCALE_asppb_authority.cer$(tput sgr0)"
	cp $crt_path/*_asppb_authority.cer $crt_path/pwd.txt $crt_path/cl-*.pfx /opt/MobileBooking
	echo
	
	echo "$(tput setaf 2)Certificate installation is complete$(tput sgr0)"
	echo

	echo "$(tput setaf 3)You should delete old client cert if it exists. Showing installed clients certs at the local user's storage...$(tput sgr0)"
	DOTNET_ROOT=/root/dotnet /root/.dotnet/tools/certificate-tool list
	echo "$(tput setaf 3)You can delete cert with command$(tput sgr0):" 'crtdelete THUMBPRINT_STRING'
	echo "$(tput setaf 3)Paste specific thumbprint instead of$(tput sgr0)" 'THUMBPRINT_STRING'
	echo
	echo "$(tput setaf 3)Don't forget to set$(tput sgr0) CipherString = DEFAULT@SECLEVEL=1$(tput setaf 3) at $(tput sgr0)/etc/ssl/openssl.cnf"

else

	echo "$(tput setaf 1)Specify the path to certificates folder! $(tput sgr0)"

fi