#!/bin/bash

export asuppk_srv_ip=$1

echo "trying to delete databases: asop, esk, pfr, mkassir"
rm /opt/MobileBooking/ASOP/*.db
rm /opt/MobileBooking/ESK/*.db
rm /opt/MobileBooking/PFR/*.db
rm /opt/MobileBooking/mkassir.db
echo "done"

if [ -z "$asuppk_srv_ip" ];
then
echo "Didn't get any ip from you. Looking for IPv4 Address of your PC"
export asuppk_srv_ip="$(echo $SSH_CLIENT | awk '{ print $1}');"
fi

echo "trying to add '$asuppk_srv_ip' to server-addr.txt"
echo $asuppk_srv_ip > /opt/MobileBooking/server-addr.txt

echo "done"