#!/bin/bash

export asuppk_srv_ip=$1

echo "trying to delete databases: asop, esk, pfr, mkassir"
rm /opt/MobileBooking/ASOP/*.db
rm /opt/MobileBooking/ESK/*.db
rm /opt/MobileBooking/PFR/*.db
rm /opt/MobileBooking/mkassir.db
echo "done"

if [ -z "$asuppk_srv_ip" ];
then echo "asuppk_srv_ip is unset";
else echo "asuppk_srv_ip is set to '$asuppk_srv_ip'";
fi

echo "trying to add '$asuppk_srv_ip' to server-addr.txt"
echo $asuppk_srv_ip > /opt/MobileBooking/server-addr.txt

echo "done"