#!/bin/bash

set -e

cd /opt/asuppk_mk105_tools/
git init
git clean -df
git reset --hard
git pull

chmod +x /opt/asuppk_mk105_tools/*
rm /opt/asuppk_mk105_tools/mk105_tools_install

echo "Update done"